[package]
name = "tree-sitter-sapvc"
version = "0.1.0"
description = "SAP VC/AVC dependency language grammar for tree-sitter"
edition = "2021"
license = "MIT"

[build-dependencies]
cc = "1.0"

[dependencies]
tree-sitter = "0.24"
tree-sitter-language = "0.1"

[lib]
name = "tree_sitter_sapvc"
path = "lib.rs"
